lesson_1
aldrk/rails_begin pull request #1
Opened 2021-04-23 15:58 UTC by aldrk

2021-04-24 08:34 UTC, VidgarVii requested changes

2021-04-24 08:34 UTC, VidgarVii commented on Gemfile
> +gem 'i18n', '~> 1.8', '>= 1.8.10'
i18n уже встроен в рельсу

2021-04-24 08:34 UTC, VidgarVii commented on README.md
> +Test
как-то мало получилось сущностей )))

список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2021-04-24 08:34 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = '1.0.0'
не стоит засорять глобальное пространство
версия относится к приложению, так что и константу нужно объявить в его контексте

посмотри к примеру в файл `config/application.rb` в какой модуль обернуто все твое приложени

```ruby
module TestGuru
  class Application < Rails::Application
    VERSION = '0.1.0'.freeze
  end
end
```

2021-04-24 08:34 UTC, VidgarVii commented on public/author.html
> +<!DOCTYPE html>
данная страница должна открываться по ссылке  /about/author

2021-04-24 08:34 UTC, VidgarVii commented on public/about.html
> +    <a href='https://www.thinknetica.com'>Thinknetica</a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке

2021-04-24 09:10 UTC, aldrk commented on README.md
> +Test
я просто думал, что ответы и вопросы будут лежать в Тесте, но сейчас представил насколько было бы неудобно это хранить

2021-04-25 14:05 UTC, VidgarVii requested changes

2021-04-26 07:14 UTC, merged