lesson_7_controller
aldrk/rails_begin pull request #13
Opened 2021-05-08 22:40 UTC by aldrk

2021-05-10 07:12 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлимо) опцию `shallow: true`
[вот](http://rusrails.ru/rails-routing#melkoe-vlozhenie) документация на русском
[вот](https://guides.rubyonrails.org/routing.html#shallow-nesting) вот на английском

2021-05-10 07:13 UTC, VidgarVii commented on config/routes.rb
> +  root to: 'questions#index', test_id: 1
логичней указать страницу списка тестов

2021-05-10 07:14 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :en
какова была причина перехода на англ язык?

2021-05-10 07:16 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = Question.create(test_params)
используй AR interface 
@test.questions.new()

2021-05-10 07:18 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = Question.create(test_params)
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо условие записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```

2021-05-10 07:18 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
def new; end

2021-05-10 13:55 UTC, VidgarVii requested changes

2021-05-10 13:55 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    render plain: Test.all.pluck(:title)
Test.pluck(:title)

2021-05-10 13:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    Question.destroy(@test.id)
тут что то странное. 
алгоритм такой
1 находим нужный вопрос
2 удаляем этот вопрос
3 редирект на страницу теста удалённого вопроса

2021-05-10 13:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :test_id)
test_id передаётся колбеком выше (find_test)
в стронг парамс передавать test_id не нужно

2021-05-10 13:55 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
Question.find(params[:id]) есть смысл положить в колбек

2021-05-11 07:09 UTC, VidgarVii requested changes

2021-05-11 07:13 UTC, aldrk commented on app/controllers/questions_controller.rb
> +  end
так там колбек есть find_question

2021-05-11 12:29 UTC, VidgarVii requested changes

2021-05-11 12:29 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    redirect_to Test.find(@question.test_id)
Строить запрос в бд таким образом нет смысла. Нужный тест можно получить через @question.test
Посмоти еще раз урок про интерфейс запросов

2021-05-18 20:13 UTC, merged