views
aldrk/rails_begin pull request #14
Opened 2021-05-19 09:33 UTC by aldrk

2021-05-19 13:40 UTC, VidgarVii requested changes

2021-05-19 13:40 UTC, VidgarVii commented on app/assets/stylesheets/index.scss
> +}
везде надо оставлять пустую строку в конце файла!
Открывай https://github.com/aldrk/rails_begin/pull/14/files и смотри где ругается гитхаб

2021-05-19 13:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  def index; end
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2021-05-19 13:40 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  end
???

2021-05-31 05:22 UTC, VidgarVii requested changes

2021-05-31 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>    before_action :find_test, only: %i[index new create]
тут index надо удалить

2021-05-31 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +      redirect_to test_questions_path
проверят в rails routes существующие пути. Там наверняка не окажется test_questions_path

2021-05-31 05:22 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    question = @test.questions.new(question_params)
данный экшен точно тестировался? Без инстанс переменных тут точно будут ошибки

2021-05-31 05:22 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @test.author = User.first
author.own_tests.build()

2021-05-31 05:22 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +
```
table
  thead
  tbody
```

2021-05-31 05:22 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +  <%= render partial: 'question_edit',  collection: @test.questions, as: :question %>
тут достаточно
= render @test.questions

2021-06-02 18:35 UTC, aldrk commented on app/controllers/questions_controller.rb
> +    question = @test.questions.new(question_params)
в смысле это вызов метода? все тестировалось

2021-06-02 18:35 UTC, aldrk commented on app/controllers/questions_controller.rb
> +    question = @test.questions.new(question_params)
я ui для этого весь и сделал

2021-08-09 09:11 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +  </tbody>
это шапка таблицы. thead
а tbody это тело таблицы. Это то что содержит render @test.questions
Так же добавь эти теги в другие таблицы

2021-08-09 20:15 UTC, merged