lesson_2_DB
aldrk/rails_begin pull request #2
Opened 2021-04-27 08:09 UTC by aldrk

2021-04-27 16:50 UTC, VidgarVii requested changes

2021-04-27 16:50 UTC, VidgarVii commented on db/migrate/20210427073746_add_null_check.rb
> +end
не надо добавлять отдельные миграции для изменения полей в одном ПР.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу.
Пример
```
t.string :title, null: false 
```

2021-04-27 16:50 UTC, VidgarVii commented on db/migrate/20210427072944_create_tests.rb
> +      t.integer :category_id
надо не просто обычное поле integer, а с указанием что нужен так же внешний ключ. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true

2021-04-27 16:50 UTC, VidgarVii commented on db/migrate/20210427072944_create_tests.rb
> +      t.integer :questions, array: true
вот связи м/у моделями как раз позволят получать нужные коллекции вопросов для конкретного теста.

2021-04-27 16:50 UTC, VidgarVii commented on db/migrate/20210427073329_create_answers.rb
> +      t.string :variants, array: true
не понятно что за варианты. 1 запись в таблице = 1 ответ. А вот текст ответа куда писать?  Я не вижу для него поля.

2021-04-27 16:50 UTC, VidgarVii commented on db/migrate/20210427073329_create_answers.rb
> +      t.integer :correct
почему integer? Ответ может быть либо верныё либо нет. А тут больше подходит булевый тип данных

2021-04-27 16:50 UTC, VidgarVii commented on db/migrate/20210427073525_create_users.rb
> +      t.integer :tests, array: true
все эти поля с array: true под удаление. Почитай про то как строятся связи в реляционных БД. Без этого нет смысла двигаться дальше

2021-04-27 16:50 UTC, VidgarVii commented on db/migrate/20210427072944_create_tests.rb
> +
нужна связь с автором теста

2021-04-27 17:31 UTC, aldrk commented on db/migrate/20210427072944_create_tests.rb
> +      t.integer :category_id
я короче думал, что это будет в след дз и в этом дз явно не указано что это нужно сделать, и в видео этого не делалось, и потому думал, что это будет дальше.

2021-04-28 15:27 UTC, VidgarVii requested changes

2021-04-28 15:27 UTC, VidgarVii commented on db/migrate/20210427072944_create_tests.rb
> +      t.integer :questions
это поле забыл удалить?!

2021-04-28 15:27 UTC, VidgarVii commented on db/migrate/20210427072944_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
лучше назвать поле author_id.
Так как по логике нам надо создать ассоциацию как автор теста
т.е. получиться
t.references :author... 
Но учти чтоб внешний ключ смотрел на таблицу юзеров
Все опции смотри тут 
https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference

2021-04-28 15:27 UTC, VidgarVii commented on db/migrate/20210427073244_create_questions.rb
> +      t.references :answers, null: false, foreign_key: true
вопрос не принадлежит ответам. Почитай про references
Тут должен быть тест

2021-04-28 15:27 UTC, VidgarVii commented on db/migrate/20210427073329_create_answers.rb
> +      t.text :text, null: false
если везде используешь название поля title. то лучше бы и это поле назвать так же. А то будешь путаться

2021-04-28 15:27 UTC, VidgarVii commented on db/migrate/20210427073525_create_users.rb
> +      t.references :tests, foreign_key: true
юзеры ни кому не принадлежат

2021-04-29 11:57 UTC, aldrk commented on db/migrate/20210427072944_create_tests.rb
> +      t.integer :questions
видимо ctrl z нажал и не заметил, прошу прощения(

2021-04-29 18:25 UTC, VidgarVii commented on db/migrate/20210427073244_create_questions.rb
> +      t.references :tests, null: false, foreign_key: true
**t.references :test**
поле надо писать в единственном числе

2021-04-29 19:00 UTC, aldrk commented on db/migrate/20210427073244_create_questions.rb
> +      t.references :tests, null: false, foreign_key: true
окей!

2021-04-29 19:00 UTC, merged