lesson_3_done
aldrk/rails_begin pull request #5
Opened 2021-05-02 19:28 UTC by aldrk

2021-05-03 13:29 UTC, VidgarVii requested changes

2021-05-03 13:29 UTC, VidgarVii commented on app/models/test.rb
> +    Test.select(:title).where(category_id: category_id).order('title DESC')
1 Согласно ДЗ надо вернуть **массив** названий теста
2 В имени метода не стоит дублировать имя класса
3 get_ так же в руби не особо принято писать. По умолчанию все методы что-то возвращают
4 здесь будет два отдельных запроса к базе, это не очень оптимально
несложно записать все в один запрос использую JOIN. Запомни простое правило. Если надо что-то получить из БД. То 100% делегируй задачу базе. Пусть данными агрегирует база. Для этого и был создан SQL. А ОРМ тебе поможет написать запрос проще и безопасней

2021-05-03 13:29 UTC, VidgarVii commented on app/models/user.rb
> +    Test.where(author_id: self).find_by(level: level)
про автора в задаче речь не шла
задачку про "пройденные тесты" правильно решать через соединительную таблицу
нужно добавить модель, к примеру `Result` или `TestsUser` и соответсвенную таблицу (`tests_users` или `results`)... или `TestPassage` и `test_passages`
в общем нужны "промежуточная модель" и "соединительная таблица"
такая таблица ("соединительная") обычно в минимальном виде хранит два внешних ключа на таблицы, которые соединяет
когда пользователь проходит тест в этой таблице должна появляться запись содержащая соответсвенно ай-ди этого пользователя и ай-ди пройденного теста
(подробней можешь посмотреть в документации к рельсам про соединительные модели, таблицы)

в простейшем варианте, который в общем-то очень часто используется, в соединительной таблице всего два поля (кроме ай-ди)
в нашем случае это будут `user_id`, `test_id` - если в таблице существует запись для пары тест-юзер, то юзер этот тест проходил (при прохождении теста нужно будет создать такую запись), если записи нет, то тест не пройден
с помощью этого механизма можно хранить информацию о прохождении любого количества тестов любым количеством пользователей

2021-05-03 13:29 UTC, VidgarVii commented on db/seeds.rb
> +Category.create([{ title: 'Backend' }, { title: 'Frontend' }, { title: 'DevOps' }])
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-05-03 13:29 UTC, VidgarVii commented on db/seeds.rb
> +Test.create([{ title: 'Rails test', level: 2, category_id: 1, author_id: 1 },
"хардкодить" `id` - не очень хорошая затея
такой "сид" невозможно накатить на существующую базу, ведь там id могут быть заняты другими записями или вовсе отсутствовать
правильней воспользоваться тем, что метод `create` возвращает созданные записи

2021-05-04 07:15 UTC, VidgarVii commented on app/models/test.rb
> +    Test
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2021-05-04 07:16 UTC, aldrk commented on app/models/test.rb
> +    Test
Окей, перед мерджем поправлю, спсибо!

2021-05-04 13:05 UTC, merged