lesson_4_associations
aldrk/rails_begin pull request #8
Opened 2021-05-04 13:33 UTC by aldrk

2021-05-04 16:30 UTC, VidgarVii requested changes

2021-05-04 16:30 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Смотри пример тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2021-05-04 16:30 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2021-05-04 16:30 UTC, VidgarVii commented on app/models/test.rb
> +    joins('JOIN categories ON tests.category_id = categories.id')
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2021-05-04 17:08 UTC, aldrk commented on app/models/category.rb
> +  has_many :tests
Намек понят!

2021-05-05 09:30 UTC, VidgarVii requested changes

2021-05-05 09:30 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
нет dependent

2021-05-05 09:30 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :users, through: :results, dependent: :destroy
в ассоциации has_many through достаточно один раз прописать dependent

2021-05-05 09:30 UTC, VidgarVii commented on config/application.rb
> +    # Configuration for the application, engines, and railties goes here.
куда дел config.i18n.default_locale = :ru ?
Если есть баг, то его надо исправить! Читай внимательно лог ошибки. Если не понятно, пиши в ЛС. Конфиг верный и нужный, просто локаль не до настроена

2021-05-07 07:39 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :questions
`dependent: ...`

2021-05-07 07:39 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, through: :results, dependent: :destroy
не исправил

**в ассоциации has_many through достаточно один раз прописать dependent**

2021-05-07 07:42 UTC, merged